version: "3.7"
services:

  front-proxy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
#    networks:
#      edge:
    ports:
    - "8080:8080"
    - "8001:8001"

  opa:
    image: openpolicyagent/opa:latest-envoy
    volumes:
      - ./policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"  # default value
#      - "--set=plugin.envoy_ext_authz_grpc.addr=:8002"
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"

  test:
    build:
      context: .
      dockerfile: Dockerfile-service-template-greeting
#    networks:
#      edge:

  template:
    build:
      context: .
      dockerfile: Dockerfile-service-template
#    networks:
#      edge:
#  test:
#    image: test:v1.0.0
   
#  template:
#    image: template:v1  
 
#networks:
#  edge:
#    name: edge